# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("GoogleCodeSearch"); Pkg.test("GoogleCodeSearch"; coverage=true)';
after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("GoogleCodeSearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
